name: Publish
run-name: ${{ github.actor }} is publishing Release ${{ github.ref_name }} 🎉

permissions:
  contents: write

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build: 
    name: Build

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.305

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

  test:
    name: Test
    needs: build

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.305

      - name: Test
        run: dotnet test --no-build

  prep-release:
    name: Prepare GitHub Release
    needs: test

    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    needs: prep-release

    strategy:
      matrix:
        os: ['linux-arm64', 'linux-x64', 'osx-arm64', 'osx-x64', 'win-arm64', 'win-x64']

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.305

      - name: Publish and package
        shell: bash
        run: |
          release_name="Chirp-${{ github.ref_name }}-${{ matrix.os }}"

          dotnet publish "src/Chirp.CLI/Chirp.CLI.csproj" -r "${{ matrix.os }}" -o "${release_name}" --sc false -p:PublishSingleFile=True

          7z a "${release_name}.zip" "${release_name}/."
          7z d "${release_name}.zip" "*.pdb"

          rm -r "${release_name}"
          
      - name: Build CSVDB Service
        run: dotnet build src/CheepService/ --configuration Release

      - name: Publish CSVDB Service
        run: dotnet publish src/CheepService/ -c Release -o ${{ env.DOTNET_ROOT }}/myapp

      - name: Populate GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "Chirp-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#   Co-Authored-By: Co-Authored-By: Oliver Flinck Sheye <189235422+osheITU@users.noreply.github.com>

