name: Publish
run-name: ${{ github.actor }} is publishing Release ${{ github.ref_name }} 🎉

permissions:
  contents: write

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build: 
    name: Build

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.305

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

  test:
    name: Test
    needs: build

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.305

      - name: Test
        run: dotnet test --no-build

  prep-release:
    name: Prepare GitHub Release
    needs: test

    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    needs: prep-release

    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          rid: linux-x64
        - os: ubuntu-latest
          rid: linux-arm64
        - os: macos-latest
          rid: osx-x64
        - os: macos-latest
          rid: osx-arm64
        - os: windows-latest
          rid: win-x64
        - os: windows-latest
          rid: win-arm64

    runs-on: ${{ matrix.os }}
  
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.305

      - name: Publish and package
        shell: bash
        run: |
          release_name="Chirp-${{ github.ref_name }}-${{ matrix.rid }}"

          dotnet publish "src/Chirp.CLI/Chirp.CLI.csproj" -r "${{ matrix.rid }}" -o "${release_name}" --self-contained false -p:PublishSingleFile=True

          if [[ "$RUNNER_OS" == "Windows" ]]; then
            powershell Compress-Archive -Path "${release_name}\*" -DestinationPath "${release_name}.zip"
            Remove-Item -Recurse -Force "${release_name}"
          else

          7z a "${release_name}.zip" "${release_name}/."
          7z d "${release_name}.zip" "*.pdb"

          rm -r "${release_name}"

      - name: Populate GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "Chirp-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
