name: Release Chirp

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish executables
        run: |
          mkdir -p release

          # Define target runtimes
          RUNTIMES=("win-x64" "osx-x64" "linux-x64" "win-arm64" "osx-arm64" "linux-arm64")

          for RUNTIME in "${RUNTIMES[@]}"; do
            OUTPUT_DIR="release/chirp-$RUNTIME"
            dotnet publish -c Release -r $RUNTIME --self-contained false /p:PublishSingleFile=true -o $OUTPUT_DIR
            zip -r "release/chirp-$RUNTIME.zip" "$OUTPUT_DIR"
          done

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: release/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
