name: Publish
run-name: ${{ github.actor }} is publishing Release ${{ github.ref_name }} 🎉

permissions:
  contents: write

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.305

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
      - name: dotnet publish
        run: dotnet publish src/CheepService/ -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload Web API Artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  test:
    name: Test
    needs: build

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.305

      - name: Test
        run: dotnet test --no-build
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_49D30E8CD1C64BC09E659A3A2D150EA6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_969FEE51D11748158290940945246D1B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DDDA483FD43C47148C69FF146B89DDA6 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bdsagroup20chirpremotedb'
          slot-name: 'Production'
          package: .


  prep-release:
    name: Prepare GitHub Release
    needs: test

    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    needs: prep-release

    strategy:
      matrix:
        os:
          [ "linux-arm64", "linux-x64", "osx-arm64", "osx-x64", "win-arm64", "win-x64",]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.305

      - name: Publish and package
        shell: bash
        run: |
          release_name="Chirp-${{ github.ref_name }}-${{ matrix.os }}"

          dotnet publish "src/Chirp.CLI/Chirp.CLI.csproj" -r "${{ matrix.os }}" -o "${release_name}" --sc false -p:PublishSingleFile=True

          7z a "${release_name}.zip" "${release_name}/."
          7z d "${release_name}.zip" "*.pdb"

          rm -r "${release_name}"
      - name: Build with dotnet
        run: dotnet build src/CheepService/ --configuration Release

      - name: dotnet publish
        run: dotnet publish src/CheepService/ -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Populate GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "Chirp-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#   Co-Authored-By: Co-Authored-By: Oliver Flinck Sheye <189235422+osheITU@users.noreply.github.com>
